#!/bin/sh

server_ip=`cat server_ip`

email=test@test.com
password=password

if [[ "x$1" != "x" ]];then
    email=$1
fi

if [[ "x$2" != "x" ]];then
    password=$2
fi

echo login account: $email, $password

echo

next_is_token=0

IFS=$'\n'
for i in `curl -d email=$email -d password=$password http://$server_ip/api/login 2>/dev/null | node parse_json.js`;do 
    echo $i
    if [[ $next_is_token = 1 ]];then
        echo ${i/    /} > /tmp/cs3_token
        next_is_token=0
    fi
    if [[ $i = "token:" ]]; then
        next_is_token=1
    fi
done
