#!/bin/bash

server_ip=`cat server_ip`

email=test@test.com
password=password

if [[ "x$1" != "x" ]];then
    email=$1
fi

if [[ "x$2" != "x" ]];then
    password=$2
fi

echo register account: $email, $password

echo 

curl -d email=$email -d password=$password http://$server_ip/api/register 2>/dev/null | node parse_json.js
