#!/bin/bash

server_ip=`cat server_ip`
tmp_token=/tmp/cs3_token

if [[ "x$2" != "x" ]];then
    token=$2
else
    if [ -f $tmp_token ]; then
        token=`cat $tmp_token`
        echo "missing token, using saved token: $token"
    fi
fi

if [[ "x$token" = "x" ]]; then
    echo "$0 <key> <token>"
    exit
fi

if [[ "x$1" != "x" ]];then
    key=$1
else
    echo "missing key, using default key: _key"
    key=_key
fi

echo

curl -d token=$token -d key=$key http://$server_ip/api/remove 2>/dev/null | node parse_json.js

