#!/bin/bash

server_ip=`cat server_ip`
tmp_token=/tmp/cs3_token

if [[ "x$1" != "x" ]];then
    token=$1
else
    if [ -f $tmp_token ]; then
        token=`cat $tmp_token`
        echo "missing token, using saved token: $token"
    fi
fi

if [[ "x$token" = "x" ]]; then
    echo "$0 <token>"
    exit
fi

echo

curl -d token=$token http://$server_ip/api/space 2>/dev/null | node parse_json.js

