#!/bin/bash

server_ip=`cat server_ip`
tmp_token=/tmp/cs3_token

if [[ "x$3" != "x" ]];then
    token=$3
else 
    if [ -f $tmp_token ]; then
        token=`cat $tmp_token`
        echo "missing token, using saved token: $token"
    fi
fi

if [[ "x$token" = "x" ]]; then
    echo "$0 <key> <file_path> <token>"
    exit
fi

if [[ "x$2" != "x" ]];then
    path=$2
else
    path=/tmp/test_upload
    echo test_upload_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx > $path
    echo "missing upload path, using default path: $path"
fi

if [[ "x$1" != "x" ]];then
    key=$1
else
    echo "missing key, using default key: _key"
    key=_key
fi

echo

curl -H "token:$token" -H "key:$key" --data-binary "@$path" http://$server_ip/api/upload 2>/dev/null | node parse_json.js

